
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
COPY 
RUN mvn clean package

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/receipt-processor.jar receipt-processor.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "receipt-processor.jar"]
